### PR TITLE
[FIX #555] FactoryBot/DynamicAttributeDefinedStatically handle wrapped dynamic values

### LINKED ISSUE #555: FactoryBot/DynamicAttributeDefinedStatically does handle dynamic values in arrays/hashes
Neither of the following cases are detected as being dynamic factory girl values
```
foo [Time.current]
foo(bar: Time.current)
```

I tried having a go at fixing it by iterating over the attribute values but it ends up marking the trait tests as an offence (if a child has an offence):

```
def_node_search :dynamic_calls, <<-PATTERN
(send ...)
PATTERN

def_node_search :attribute_values, <<-PATTERN
(send nil? _ $...)
PATTERN

def_node_search :factory_attributes, <<-PATTERN
(block (send nil? {:factory :trait} ...) _ { (begin $...) $(send ...) } )
PATTERN

def on_block(node)
  return if node.method_name == :trait
  factory_attributes(node).to_a.flatten.each do |attribute|
    attribute_values(attribute).to_a.flatten.each do |value|
      next if dynamic_calls(value).to_a.none?
      add_offense(attribute, location: :expression)
    end
  end
end
```

fails the trait spec with:

```
        factory :post do
          title "Something"
          trait :published do
+         ^^^^^^^^^^^^^^^^^^^ Use a block to set a dynamic value to an attribute.
            published_at 1.day.from_now
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use a block to set a dynamic value to an attribute.
          end
```

I suspect the fix might be to check if the `attribute` root node is a trait, and if so, get the child and add the offence to that? Thoughts?

### PR DESCRIPTION
**Pull request by abrom**
There are some edge cases relating to dynamic attributes not being detected when inside an array or hash, as per below:

```
# bad
recent_status_updates [1.hour.ago]
meta_tags(first_payment: 5.minutes.ago)

# good
recent_status_updates { [1.hour.ago] }
meta_tags { { first_payment: 5.minutes.ago } }
```

This change detects these edge cases and handles them appropriately.

Fixes #555 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) is passing.

### CODE REVIEW

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 1]
```diff
@@ -41,15 +41,20 @@ class DynamicAttributeDefinedStatically < Cop
...
+              next if values.nil?
+              next if values.all? { |v| v.recursive_literal? || v.const_type? }
+              add_offense(attribute, location: :expression)
             end
           end
 
           def autocorrect(node)
             if method_uses_parens?(node.location)
-              autocorrect_replacing_parens(node)
+              if value_is_inferred_hash?(node.descendants.first)
```
Comment (abrom) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: Check for `attribute(foo: bar)` => `attribute { { foo: bar } }`

**Comment by abrom** [comment]
Following on from your suggestion in #554 @jonatas, this change should handle the various edge cases. Your suggestion would work, although I believe it would get caught up if there were additional levels of arrays? `foo [[Time.now]]` ??

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 2]
```diff
@@ -41,15 +41,20 @@ class DynamicAttributeDefinedStatically < Cop
           def on_block(node)
             return if node.method_name == :trait
             factory_attributes(node).to_a.flatten.each do |attribute|
-              if dynamic_defined_statically?(attribute)
-                add_offense(attribute, location: :expression)
-              end
+              values = value_matcher attribute
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: for consistency, `value_matcher(attribute)`

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 3]
```diff
@@ -41,15 +41,20 @@ class DynamicAttributeDefinedStatically < Cop
...
+              next if values.nil?
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: when the value is either nil or array, I prefer just to cast it to `to_a`
`next if values.to_a.all?`
also I would add a helper method `static?` which encapsulates recursive_literal? || const_type? check

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 4]
```diff
@@ -62,10 +67,20 @@ def method_uses_parens?(location)
             location.begin.source == '(' && location.end.source == ')'
           end
 
-          def autocorrect_replacing_parens(node)
+          def value_is_inferred_hash?(value)
+            value.type == :hash && value.location.begin.nil?
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: `value.hash_type? && value.location.begin.nil?` but what is an inferred hash anyway?
maybe you want to check for `value.hash_type? && value.braces?`

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 5]
```diff
@@ -62,10 +67,20 @@ def method_uses_parens?(location)
...
+          end
+
+          def autocorrect_inferred_hash(node)
+            autocorrect_replacing_parens node, ' { { ', ' } }'
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: `autocorrect_replacing_parens(node, ' { { ', ' } }')`

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb [hunk 6]
```diff
@@ -30,8 +30,8 @@ module FactoryBot
         class DynamicAttributeDefinedStatically < Cop
           MSG = 'Use a block to set a dynamic value to an attribute.'.freeze
 
-          def_node_matcher :dynamic_defined_statically?, <<-PATTERN
-          (send nil? _ (send ... ))
+          def_node_matcher :value_matcher, <<-PATTERN
+          (send nil? _ $...)
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: this should be indented with 2 spaces

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb (hunk 4 above)
Comment (abrom) [reply lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: Great, thanks! Still learning the node helpers 👍 Although I'm thinking you mean `value.hash_type? && !value.braces?` ?

By inferred hash I was attempting to describe a hash defined without braces (ie as a function parameter).

`foo(bar: 'baz')` vs `foo({ bar: 'baz' })`

The issue being, if the hash is defined without braces, we need to give it some when correcting the result and putting it into a block

**Comment by abrom** [comment]
Regarding the extra tests, surely can. Although the accepts constants check is already there 

https://github.com/backus/rubocop-rspec/pull/556/files#diff-6fcbfafcbb24f7fa5e8cbbcfa6941499R58

`tag Tag::MAGIC`

File: lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb (hunk 4 above)
Comment (abrom) [reply lib/rubocop/cop/rspec/factory_bot/dynamic_attribute_defined_statically.rb]: Changing the method name to `value_hash_without_braces?` to avoid confusion

**Comment by Darhazer** [comment]
Can you please rebase so I can merge this?

**Comment by abrom** [comment]
Done 👍

**Comment by jonatas** [comment]
@abrom I don't think people will use such syntax.

We can create a [recursive build in search](https://rubocop.readthedocs.io/en/latest/node_pattern/#composing-complex-expressions-with-multiple-matchers) to check it and also cover hashes. But it's like a very rare case.

**Comment by Darhazer** [comment]
Sorry @abrom can I ask you to rebase one more time, as there was a problem with the build and I was unable to merge

**Comment by abrom** [comment]
No probs, done 👍
