### PR TITLE
Fix RSpec/DescribedClass with empty block

### LINKED ISSUE #541: An error occurred while RSpec/DescribedClass cop
Steps to reproduce:

1. Clone this repo: https://github.com/mensfeld/broken-rubocop-rspec
2. Bundle
3. bundle exec rubocop

See:

```bash
Inspecting 2 files
.An error occurred while RSpec/DescribedClass cop was inspecting /home/user/example/spec/broken_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
C

Offenses:

spec/broken_spec.rb:1:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
describe Broken do
^^^^^^^^^^^^^^^

2 files inspected, 1 offense detected

1 error occurred:
An error occurred while RSpec/DescribedClass cop was inspecting /home/user/example/spec/broken_spec.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.0 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by bquorning**
Fixes #541.

`RSpec/DescribedClass` cop would raise an exception when encountering an empty `describe` block.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) is passing.

### CODE REVIEW

File: lib/rubocop/cop/rspec/described_class.rb [hunk 1]
```diff
@@ -79,6 +79,8 @@ def autocorrect(node)
         private
 
         def find_usage(node, &block)
+          return if node.nil?
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/described_class.rb]: IMO the return should be in the `on_block`, before even trying to find the usage inside the body

Comment (bquorning) [reply lib/rubocop/cop/rspec/described_class.rb]: Thank you – I was wondering about exactly that.
